### ISSUE TITLE
How to used like SubCollection

### ISSUE THREAD

**Issue by alialnaghmoush** [moh-abdullah-it/firestore_model#1]
مرحبا أ. محمد

كيف أقدر أستخدمه مع SubCollection
مثلا عندي كولكشن أسمه 
clients
داخله دكيومنت
 في هذا الدكيومنت هنا أرغب في عمل الكولكشن وانشاء الدكيومنت عن طريق أضافتك الجميلة

**Comment by moh-abdullah-it** [comment]
مرحبا اخي:
حاليا اعمل علي اصدار نسخة جديدة تقدم الدعم والتعامل مع SubCollections
شكر لتجربتك  للاضافة ونرحب باي تعليق او ملاحظة لا تردد في التواصل معنا في اي وقت

**Comment by moh-abdullah-it** [comment]
بداية من النسخة 0.8.0 
 تقدر تتعامل مع SubCollection
