### ISSUE TITLE
Cupertino App Error [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

### ISSUE THREAD

**Issue by fpatelm** [moh-abdullah-it/firestore_model#18]
@moh-abdullah-it :

Context:
Using CupertinoApp() on iOS.
Using firebase emulators (firestore)

```
Future<void> main() async {
  await FirebaseApp.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
    settings: FirestoreModelSettings(
      host: '0.0.0.0',
    ),
  );
  FirestoreModel.injectAll([UserData()]);

  if (USE_EMULATOR) {
    _connectToFirebaseEmulator();
  }

  runApp(MyApp());
}
```

Firestore rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2050, 10, 1);
    }
  }
}
```

On the iOS emulator, settings, _Allow HTTP Services_, is enabled.

When using the FirestoreModel API I get the following errors:

**Error 1:**
PlatformException (PlatformException(unavailable, The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff., {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff., nativeErrorMessage: Failed to get document because the client is offline., nativeErrorCode: 14}, null))

**Error 2:**
FirebaseException ([cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.)

**Error 3:**
flutter: Error [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

Info:
Disable the firebase emulators, gives the same error.

**Comment by moh-abdullah-it** [comment]
i success run package with use MaterialApp in ios & android  no issues founded.

i well test it with CupertinoApp

**Comment by moh-abdullah-it** [comment]
and i upgrade example to use DefaultFirebaseOptions

**Comment by moh-abdullah-it** [comment]
its work fine with CupertinoApp.
 i will test firebase emulators

**Comment by fpatelm** [comment]
@moh-abdullah-it  I restarted the computer and now seems to work. It looks like ports were corrupted and thus communication to firebase was down. This case can be closed. Appreciate your support.
