### ISSUE TITLE
firebase_options.dart missing in example

### ISSUE THREAD

**Issue by tksoh** [moh-abdullah-it/firestore_model#19]
Greeting. I tried to build the example, but the firebase_options.dart file seems to be missing in the lib folder. Perhaps it was left out when in the last commit?

commit de7d630bd8b0a4336685f278a09807497b837710 (master)
Author: Mohamed Abdullah <moh.abdullah.it@gmail.com>
Date:   Fri Nov 18 16:35:29 2022 +0300

    [MOD]: upgrade example to use DefaultFirebaseOptions

**Comment by moh-abdullah-it** [comment]
hi @tksoh this file configuration for firebase.
you can follow steps here to generate you files

https://firebase.flutter.dev/docs/overview
