### ISSUE TITLE
تعديلات مع اضافات بسيطة

### ISSUE THREAD

**Issue by alialnaghmoush** [moh-abdullah-it/firestore_model#2]
مرحبا معاك علي

أولا عند حفظ 
Collections 
يحفظه كا CamelCase 
والمفترض يحفظ
 lowercace او SnakeCase 
او اول حرف صغير والباقي
 CamelCase 
افضل لتنسيق الداتا

ثانيا لمه يكتب الكلاس يكتب بصيغة المفرد بالعادة ولكن في الداتابيس 
يكتب بصيغة الجمع اذا امكن تحويل الكلمة الى كلمة بصيغة الجمع بشكل تلقائي يكون افضل بكثير

يمكنك الاستعانه بهذا المكتبه

[inflection](https://pub.dev/packages/inflection3)

**Comment by moh-abdullah-it** [comment]
يا هلا اخي 
شكرا علي اقتراحك 
وبالفعل هو في خطة تطوير المكتبة ومن الممكن انه يكون في الاصدار القادم
في الوقت الحالي يتم استخدام اسم الكلاس بشكل مباشر كما هو 
مع امكانية انك تغير اسم  ال
Collection
 collectionName => 'your_collection_name';
او
SubCollection 
subCollectionName => 'your_sub_collection_name';
